# -*- coding: utf-8 -*-
"""002 Conditionals and Loops.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YVZIwQaqtRhqwbG51eKc08pGXJl210zS

# **if else Condition**

**Find number is negative, positive or zero**
"""

# Commented out IPython magic to ensure Python compatibility.
# %%writefile condition1.cpp
# 
# #include<iostream>
# using namespace std;
# int main(){
#   int n;
#   cin >> n;
#   if (n>0){
#     cout << "positive";
#   }
#   else if (n<0){
#     cout << "negative";
#   }
#   else{
#     cout << "zero";
#   }
# }

!g++ condition1.cpp -o condition1
!./condition1

"""**Which on is greater**"""

# Commented out IPython magic to ensure Python compatibility.
# %%writefile condition2.cpp
# 
# #include<iostream>
# using namespace std;
# int main(){
#   int a,b;
#   cin >> a >> b;
#   if (a>b){
#     cout << "a is greater";
#   }
#   else{
#     cout << "b is greater";
#   }
# }

!g++ condition2.cpp -o condition2
!./condition2

"""**Print "lowwer case" if char is between a-z, print "upper case" if char is between A-Z, else in between 0-9 print "numeric"**"""

# Commented out IPython magic to ensure Python compatibility.
# %%writefile condition3.cpp
# 
# #include<iostream>
# using namespace std;
# int main(){
#   char c;
#   cout<<"Enter a character: ";
#   cin>>c;
#   if (c>='a' && c<='z'){
#     cout<<"lower case";
#   }
#   else if (c>='A' && c<='Z'){
#     cout<<"upper case";
#   }
#   else{
#     cout<<"numeric";
#   }
# }

!g++ condition3.cpp -o condition3
!./condition3

"""# **Loops**

**Print number from 1 to n**
"""

# Commented out IPython magic to ensure Python compatibility.
# %%writefile loop1.cpp
# 
# #include<iostream>
# using namespace std;
# int main(){
#   int n;
#   cin >>n;
#   int i=1;
#   while (i<=n){
#     cout << i << " ";
#     i++;
#   }
# }

!g++ loop1.cpp -o loop1
!./loop1

"""**Sum of number from 1 to n**"""

# Commented out IPython magic to ensure Python compatibility.
# %%writefile loop2.cpp
# 
# #include<iostream>
# using namespace std;
# int main(){
#   int n;
#   int sum = 0;
#   cin >>n;
#   int i=1;
#   while (i<=n){
#     sum+=i;
#     i++;
#   }
#   cout<<sum;
# }

!g++ loop2.cpp -o loop2
!./loop2

"""**Sum of even number from 1 to n**"""

# Commented out IPython magic to ensure Python compatibility.
# %%writefile loop3.cpp
# 
# #include<iostream>
# using namespace std;
# int main(){
#   int n;
#   cin >>n;
#   int sum = 0;
#   int i=1;
#   while (i<=n){
#     if (i%2==0){
#       sum+=i;
#     }
#     i++;
#   }
#   cout<<sum;
# }

!g++ loop3.cpp -o loop3
!./loop3

"""**Feranhite to celcious conversion**"""

# Commented out IPython magic to ensure Python compatibility.
# %%writefile loop4.cpp
# 
# #include<iostream>
# using namespace std;
# int main(){
#   int f;
#   cin >>f;
#   int c;
#   c = (f-32)*5/9;
#   cout<<c;
# }

!g++ loop4.cpp -o loop4
!./loop4

"""**Check number n is prime or not**"""

# Commented out IPython magic to ensure Python compatibility.
# %%writefile loop5.cpp
# 
# #include<iostream>
# using namespace std;
# int main(){
#   int n;
#   cin >>n;
#   int i=2;
#   while (i<n){
#     if (n%i==0){
#       cout<<"not prime";
#       return 0;
#     }
#     i++;
#   }
#   cout<<"prime";
# }

!g++ loop5.cpp -o loop5
!./loop5